In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df_raw = pd.read_parquet('../Data/data_2024-04-10_2026-04-10.parquet')
df_raw.describe()

,block_number,base_fee_per_gas,gas_used,gas_limit,transaction_count,size
count,5.224088e+06,5.224088e+06,5.224088e+06,5.224088e+06,5.224088e+06,5.224088e+06
mean,2.223356e+07,4.579468e+09,2.000778e+07,3.954351e+07,2.022691e+02,1.015016e+05
std,1.508064e+06,9.739521e+09,1.081743e+07,1.108291e+07,1.106095e+02,6.472966e+04
min,1.962152e+07,8.703865e+06,0.000000e+00,2.997070e+07,0.000000e+00,1.151000e+03
25%,2.092754e+07,2.458945e+08,1.293229e+07,3.000000e+07,1.380000e+02,6.172600e+04
50%,2.223356e+07,1.081608e+09,1.746895e+07,3.596484e+07,1.790000e+02,8.553950e+04
75%,2.353958e+07,5.793104e+09,2.481927e+07,4.500000e+07,2.390000e+02,1.245750e+05
max,2.484560e+07,8.255167e+11,6.005850e+07,6.011724e+07,2.753000e+03,1.956743e+06

In [3]:
df_oracle = pd.read_parquet('../Data/transitions_v23.parquet') 
print(df_oracle.columns)

Index(['action', 'reward', 'done', 'episode_id', 'timestamp', 'step_index',
       'gas_t', 'gas_reference', 'transaction_count', 'queue_size',
       'time_to_deadline', 'executed_volume_proxy', 'truncated', 'info_json',
       'behavior_log_prob', 'policy_type', 's_gas_t0', 'ns_gas_t0', 's_gas_t1',
       'ns_gas_t1', 's_gas_t2', 'ns_gas_t2', 's_congestion', 'ns_congestion',
       's_momentum', 'ns_momentum', 's_accel', 'ns_accel', 's_surprise',
       'ns_surprise', 's_backlog', 'ns_backlog', 's_queue', 'ns_queue',
       's_time_left', 'ns_time_left', 's_gas_ref', 'ns_gas_ref'],
      dtype='str')

In [ ]:
df_oracle

,action,reward,done,episode_id,timestamp,step_index,gas_t,gas_reference,transaction_count,queue_size,...,s_surprise,ns_surprise,s_backlog,ns_backlog,s_queue,ns_queue,s_time_left,ns_time_left,s_gas_ref,ns_gas_ref
0,4,0.000000,0,0,2024-04-10 00:00:11+00:00,0,1.711158e+10,1.711158e+10,256.0,26.0,...,0.304204,0.258180,0.000000,0.000000,0.094545,5.818182e-02,1.000000,0.999861,0.037705,0.038124
1,4,-0.304425,0,0,2024-04-10 00:00:23+00:00,1,1.749211e+10,1.730184e+10,162.0,16.0,...,0.258180,0.272414,0.000000,0.000000,0.058182,6.181818e-02,0.999861,0.999722,0.038124,0.037903
2,4,0.340676,0,0,2024-04-10 00:00:35+00:00,2,1.700125e+10,1.720165e+10,171.0,17.0,...,0.272414,0.361054,0.000000,0.034399,0.061818,9.454545e-02,0.999722,0.999583,0.037903,0.037592
3,4,1.101294,0,0,2024-04-10 00:00:47+00:00,3,1.663688e+10,1.706045e+10,257.0,26.0,...,0.361054,0.228923,0.034399,0.001842,0.094545,4.727273e-02,0.999583,0.999444,0.037592,0.038051
4,4,-1.081782,0,0,2024-04-10 00:00:59+00:00,4,1.810063e+10,1.726849e+10,126.0,13.0,...,0.228923,0.262005,0.001842,0.000000,0.047273,5.454545e-02,0.999444,0.999305,0.038051,0.038039
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5224083,4,0.002790,0,729,2026-04-09 23:59:11+00:00,7166,5.103682e+07,5.219925e+07,239.0,24.0,...,0.326794,0.288524,0.035414,0.016830,0.087273,6.181818e-02,0.000556,0.000417,0.000075,0.000075
5224084,4,-0.000162,0,729,2026-04-09 23:59:23+00:00,7167,5.227055e+07,5.217538e+07,171.0,17.0,...,0.288524,0.293117,0.016830,0.039685,0.061818,6.545454e-02,0.000417,0.000278,0.000075,0.000075
5224085,4,0.005278,0,729,2026-04-09 23:59:35+00:00,7168,4.921271e+07,5.214520e+07,180.0,18.0,...,0.293117,0.263177,0.039685,0.011996,0.065455,4.727273e-02,0.000278,0.000139,0.000075,0.000075
5224086,4,-0.004119,0,729,2026-04-09 23:59:47+00:00,7169,5.536154e+07,5.219310e+07,126.0,13.0,...,0.263177,0.324948,0.011996,0.009179,0.047273,8.727273e-02,0.000139,0.000000,0.000075,0.000075
5224087,4,0.001308,1,729,2026-04-09 23:59:59+00:00,7170,5.161866e+07,5.216370e+07,235.0,24.0,...,0.324948,0.324948,0.009179,0.009179,0.087273,-4.127208e-11,0.000000,0.000000,0.000075,0.000075

:

In [4]:
import d3rlpy.algos as algos
print("DiscreteAWAC" in dir(algos))

False

In [5]:
import d3rlpy
print([name for name in dir(d3rlpy.algos) if name.startswith("Discrete") and "Config" in name])

['DiscreteBCConfig', 'DiscreteBCQConfig', 'DiscreteCQLConfig', 'DiscreteDecisionTransformerConfig', 'DiscreteRandomPolicyConfig', 'DiscreteSACConfig']